services:
  web:
    build:
      context: .
      dockerfile: MiraGamesBackend/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - .:/app
      - ~/.dotnet/tools:/root/.dotnet/tools
      - ~/.nuget/packages:/root/.nuget/packages
      - ~/.aspnet/https:/https:ro
    stdin_open: true
    tty: true
    command: dotnet run --urls http://0.0.0.0:8080 --non-interactive --project MiraGamesBackend